# Generated by Django 5.2.7 on 2025-11-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграмм чат id",
                max_length=100,
                null=True,
                verbose_name="Телеграмм чат id",
            ),
        ),
    ]
