# Generated by Django 5.2.7 on 2025-11-01 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения",
                        max_length=100,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Дата и время следующего выполнения (в формате YYYY-MM-DD HH:MM:SS",
                        verbose_name="Время следующего выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие - саму привычку",
                        max_length=300,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Добавьте периодичность выполнения в днях (по умолчанию ежедневно)",
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение за выполнение полезной привычки",
                        max_length=300,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_do",
                    models.PositiveIntegerField(
                        help_text="Добавьте время на выполнение в секундах",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Определите, будет ли публикация публичной",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная приятная привычка (только для полезных привычек)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "place", "time", "action"),
                        name="unique_habit_for_user",
                    )
                ],
            },
        ),
    ]
