# Generated by Django 5.2.7 on 2025-10-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения",
                        max_length=100,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время выполнения",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие - саму привычку",
                        max_length=300,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Добавьте периодичность выполнения в днях (по умолчанию ежедневно)",
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        help_text="Вознаграждение за выполнение полезной привычки",
                        max_length=300,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_do",
                    models.PositiveIntegerField(
                        help_text="Добавьте время на выполнение",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Определите, будет ли публикация публичной",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная приятная привычка (только для полезных привычек)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Приятная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
